# -*- coding: utf-8 -*-
"""Frozen_lake(RL)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDWY3bsLz5Y7jY0fbAPfORssdQP3oUCC
"""

!pip install gym

!pip install IPython

import numpy as np
import gym
import random
import time
from IPython.display import clear_output , display

env=gym.make("FrozenLake-v1")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print("Action space size:", action_space_size)
print("State space size:", state_space_size)

q_table = np.zeros((state_space_size, action_space_size))
print("Initial Q-table:\n", q_table)

num_episodes = 10000
max_steps_per_episode = 1000
learning_rate = 0.01  # alpha
discount_rate = 0.99  # gamma

exploration_rate = 1  # epsilon greedy strategy
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        # Take the action and observe the outcome
        new_state, reward, done, info = env.step(action)

        # Update the Q-table using the Q-learning formula
        q_table[state, action] = (1 - learning_rate) * q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the new state
        state = new_state

        # Accumulate the reward
        rewards_current_episode += reward

        if done:
            break

    # Decay the exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    # Append the reward of the current episode
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("Average reward per thousand episodes:\n")

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r) / 1000))
    count += 1000

# Display the final Q-table
print("\n\n*****Final Q-table:*****\n")
print(q_table)

for episode in range(3):
    state = env.reset()
    done = False
    print("****CHAPTER", episode + 1, "******\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        print(env.render(mode='ansi'))  # Render the environment in 'ansi' mode for text output
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        state = new_state  # Update the state to the new state

        if done:
            clear_output(wait=True)
            print(env.render(mode='ansi'))
            if reward == 1:
                print("SUCCESS !!")
                time.sleep(3)
            else:
                print("FAILURE !!")
                time.sleep(3)
            clear_output(wait=True)
            break

            state = new_state

env.close()

